---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Media:
    - Radaar:
        href: http://radarr.asbblog.com/
        description: Radaar 
        icon: radaar
    - QbTorrent: 
        href: http://qb.asbblog.com/
        description: Bit torrent 
        icon: qbittorrent
    - Jelly: 
        href: http://jelly.asbblog.com/
        description: Jelly 
        icon: jellyfin
- Media2: 
    - Sonarr: 
        href: http://sonarr.asbblog.com/
        description: Sonnar
        siteMonitor: http://sonarr.asbblog.com/
        icon: sonarr
    - kodi: 
        href: http://kodi.asbblog.com/
        description: kodi
        icon: kodi
    - kodi2: 
        href: http://kodi2.asbblog.com/
        description: kodi2 
        icon: kodi
       

- Monitoring:
    - Pi One:
        href: http://pi.asbblog.com/admin
        description: pi hole - main 
        icon: pi-hole
        siteMonitor: https://pi.asbblog.com/admin
    - Pi two:
        href: http://pi2.asbblog.com/
        description: pi2 hole - main 
        siteMonitor: https://pi2.asbblog.com/admin
        icon: pi-hole

- Storage system:
    - NAS:
        href: http://unraid.asbblog.com/login/
        description: Unraid 
        siteMonitor: https://unraid.asbblog.com/login
        icon: unraid
    - NAS: 
        href: http://nas1.asbblog.com/
        description: synology 
        siteMonitor: https://nas1.asbblog.com/signin/
        icon: si-synology

- Automation:
    - Home: 
        href: http://home.asbblog.com
        description: Home Assistance for home
        icon: home-assistant 
        widget:
            type: homeassistant
            url: http://home.asbblog.com
            key: access_token
    - Casaos: 
        href: http://casos.asbblog.com
        description : Casaos Asbblog 
        icon: casaos 
    - Casaos Ubuntu: 
        href: http://ubuntu2.asbblog.com/
        descripition: Casaos Ubuntu 
        icon: casaos
- Other: 
    - Calander: 
        widget:
            type: calendar
            firstDayInWeek: sunday # optional - defaults to monday
            view: monthly # optional - possible values monthly, agenda
            maxEvents: 10 # optional - defaults to 10
            showTime: true # optional - show time for event happening today - defaults to false
            timezone: America/Los_Angeles # optional and only when timezone is not detected properly (slightly slower performance) - force timezone for ical events (if it's the same - no change