---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- My Apps:
    - My First Service:
        href: https://ashy-hill-0d4183f0f.3.azurestaticapps.net/
        description: Homepage is awesome

- News:
    - Brutalist Report:
        href: https://brutalist.report/

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎
