---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Media:
    - Radaar:
        href: http://radarr.asbblog.com/
        description: Radaar 
    - QbTorrent: 
        href: http://qb.asbblog.com/
        description: Bit torrent 
    - Jelly: 
        href: http://jelly.asbblog.com/
        description: Jelly 
        icon: si-jelly
    - Sonnar: 
        href: http://radarr.asbblog.com/
        description: Sonnar
        siteMonitor: http://radarr.asbblog.com/
        icon: si-sonnar
    - kodi: 
        href: http://kodi.asbblog.com/
        description: kodi
        icon: kodi
    - kodi2: 
        href: http://kodi2.asbblog.com/
        description: kodi2 
        icon: kodi
       

- Monitoring:
    - Pi One:
        href: http://pi.asbblog.com/admin
        description: pi hole - main 
        icon: pi-hole
        siteMonitor: https://pi.asbblog.com/admin
    - Pi two:
        href: http://pi2.asbblog.com/
        description: pi2 hole - main 
        siteMonitor: https://pi2.asbblog.com/admin
        icon: pi-hole

- Storage system:
    - NAS:
        href: http://unraid.asbblog.com/
        description: Unraid 
        siteMonitor: https://unraid.asbblog.com
    - NAS: 
        href: http://nas1.asbblog.com/
        description: synology 
        siteMonitor: https://nas1.asbblog.com/

- Automation:
    - Home: 
        href: http://home.asbblog.com
        description: Home Assistance for home
    - Casaos: 
        href: http://casos.asbblog.com
        description : Casaos Asbblog 
    - Casaos Ubuntu: 
        href: http://ubuntu2.asbblog.com/
        descripition: Casaos Ubuntu 
