---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Media:
    - Radarr:
        href: https://radarr.asbblog.com/
        description: Radarr 
        icon: radarr
        siteMonitor: https://radarr.asbblog.com/
        widget:
            type: radarr
            url: https://radarr.asbblog.com
            key: 89786ab3384c4a748562df01b485b49c
            enableQueue: true
    - QbTorrent: 
        href: https://qb.asbblog.com/
        description: Bit torrent 
        icon: qbittorrent
        siteMonitor: http://qb.asbblog.com/
        widget:
            type: qbittorrent
            url: http://qb.asbblog.com
            username: admin
            password: adminadmin
    - jellyseerr: 
        href: http://jelly.asbblog.com/
        description: jellyseerr 
        icon: jellyseerr
        siteMontior: http://jelly.asbblog.com
        widget:
            type: jellyseerr
            url: http://jelly.asbblog.com
            key: MTcwMzcxMzUwNTY1NWQwZWUyODNlLWVhYmEtNDllOS05ZDFhLTVmMDY5NTVhYjhhMg==
    - Sonarr: 
        href: http://sonarr.asbblog.com/
        description: Sonnar
        siteMonitor: http://sonarr.asbblog.com/
        icon: sonarr
        widget:
            type: sonarr
            url:  http://sonarr.asbblog.com
            key: d9d1f45e906d4564a0563f792ca4b37b
            enableQueue: true # optional, defaults to false
    - prowlarr: 
        href: http://prowlarr.asbblog.com
        description: prowlarr
        icon: prowlarr
        widget:
            type: prowlarr
            url: http://prowlarr.asbblog.com
            key: apikeyapikeyapikeyapikeyapikey
    - kodi: 
        href: http://kodi.asbblog.com/
        description: kodi
        icon: kodi
    - kodi2: 
        href: http://kodi2.asbblog.com/
        description: kodi2 
        icon: kodi
- Monitoring:
    - Pi One:
        href: http://pi.asbblog.com/admin
        description: pi hole - main 
        icon: pi-hole
        siteMonitor: https://pi.asbblog.com/admin
        widget:
            type: pihole
            url: https://pi.asbblog.com
            key: d5cee877ac04b8c52c6a182d64781fa30bf3a00d590af20a70bc82f0037bd55e
    - Pi two:
        href: http://pi2.asbblog.com/admin
        description: pi2 hole - main 
        siteMonitor: https://pi2.asbblog.com/admin
        icon: pi-hole
        widget:
            type: pihole
            url: https://pi2.asbblog.com
            key: 3cecde64f6a16ebb7833b98e00f7ebd5bb7a2db73844d6977448eaf697d45e02
- Storage Server:
    - NAS:
        href: http://unraid.asbblog.com/login/
        description: Unraid 
        siteMonitor: https://unraid.asbblog.com/login
        icon: unraid
    - NAS: 
        href: http://nas1.asbblog.com/
        description: synology 
        siteMonitor: https://nas1.asbblog.com/signin/
        icon: si-synology
- Automation:
    - Home: 
        href: https://home.asbblog.com
        description: Home Assistance for home
        icon: home-assistant 
        siteMonitor: https://home.asbblog.com
        widget:
            type: homeassistant
            url: https://home.asbblog.com
            key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIzZGZkZDUzM2EwMWY0N2ZmYjViYmZmZTZmNGI0NDgwNSIsImlhdCI6MTcwNzkzODA2MywiZXhwIjoyMDIzMjk4MDYzfQ.SzfzMZnVBsexBFO2VIFZQekmN7CnrMd0Ld28sgFe-TI
            custom:
                 - state: light.hue_play_gradient_lightstrip_1
                   label: TV Light strip status 
                 - state: light.signe_gradient_floor_main_room
                   label: Lamp main room 
                 - template: "{{ sensor.air_quality_monitor_carbon_dioxide }}"
                   label: carbon monoxide 
                   value: "{attributes.measurement}"
                 - state: lock.ix_xdrive50_lock
                   label: Car is locked 
                   
    - Casaos: 
        href: http://casos.asbblog.com
        description : Casaos Asbblog 
        icon: casaos 
    - Casaos Ubuntu: 
        href: http://ubuntu2.asbblog.com/
        descripition: Casaos Ubuntu 
        icon: casaos
- Business:
    - Vikunja:
        href: http://vj.asbblog.com/
        description: Project management tool 
        icon: vikunja
        siteMonitor: http://vj.asbblog.com/
    - Books:
        href: https://books.asbsolutionsgroup.com
        description: Zoho Books for timesheet and invocing
        icon: zoho-books
        siteMonitor: https://books.asbsolutionsgroup.com/
    - Ceipal:
        href: https://talenthire.ceipal.com/signin/
        description: CEIPAL for candidate and job management. 
    - IT Tools:
        href:  https://tools.asbblog.com/
        description: IT Tools for the developers
- Other: 
    - Calander: 
        widget:
            type: calendar
            firstDayInWeek: sunday # optional - defaults to monday
            view: monthly # optional - possible values monthly, agenda
            maxEvents: 10 # optional - defaults to 10
            showTime: true # optional - show time for event happening today - defaults to false
            timezone: America/Los_Angeles # optional and only when timezone is not detected 
   